version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: rpgmaker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rpgmaker123
      MYSQL_DATABASE: rpgmaker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rpgmaker-api:
    container_name: rpgmaker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=rpgmaker;User=root;Password=ab12c3;"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
